<table>
	<tr><td><strong>{nom}</strong></td><td>{prenom}</td></tr>
	<tr><td>{sexe}</td><td>{datenaissance}</td></tr>
	<tr><td>{telportable}</td></tr>
	<tr><td>{teldomicile}</td></tr>
	<tr><td>{email}</td></tr>
	<tr><td>{nosecu}</td><td>{fichesanitaire}</td></tr>
	<tr><td>{nosecu}</td><td>{fichesanitaire}</td></tr>
	<tr><td>{sansviandesansporc}</td><td>{autorisationsortie}</td></tr>
</table>
